[build]
  command = "npm run build"
  publish = "dist"

# Proxy API requests to the backend
[[redirects]]
  from = "/api/*"
  to = "https://app.apextrading.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200